//! The application logo.
//!
//! `assets/logo.svg` is the single source of truth. Its bubble artwork is
//! *traced from the real WeChat icon* by `tools/trace_icon.py` (which pulls the
//! icon out of Weixin.exe), so it matches the official mark; the download badge
//! in the bottom-right corner is added by that script on top.
//!
//! `build.rs` rasterizes the SVG to a true-colour PNG at compile time, because
//! GPUI's SVG renderer only paints a monochrome alpha mask tinted by a single
//! colour. The PNG is served by [`crate::assets::AppAssets`] under
//! [`crate::assets::LOGO_PATH`] and drawn in the title bar. To review the
//! artwork, open the generated `target/debug/build/wx_downloader-*/out/logo.png`.

#[cfg(test)]
mod tests {
    use crate::assets;

    fn svg_text() -> &'static str {
        std::str::from_utf8(assets::logo_svg_bytes()).expect("logo.svg is UTF-8")
    }

    /// Byte offset of the one big traced bubble path.
    fn bubble_path_start(svg: &str) -> usize {
        svg.find(r##"fill-rule="evenodd""##)
            .expect("the traced bubble path")
    }

    /// The badge: a green disc with a white download arrow, in the bottom-right.
    #[test]
    fn logo_has_a_download_badge_in_the_corner() {
        let svg = svg_text();

        let badge = svg
            .find(r##"<circle cx="40.2" cy="40.2""##)
            .expect("a badge disc in the bottom-right");
        // Bottom-right quadrant of the 48x48 viewBox.
        assert!(
            badge > bubble_path_start(svg),
            "the badge must be drawn on top of the bubbles"
        );
        // A downward arrow sits inside the disc, which makes it a *download*.
        let arrow = svg.find(r##"M38.35 39.9 40.2 41.75l1.85-1.85Z"##);
        assert!(arrow.is_some(), "download arrow not found");
        assert!(arrow.unwrap() > badge, "the arrow belongs to the badge");
    }

    /// The artwork is traced from the official icon, so it must be recorded as
    /// generated rather than look hand-edited — otherwise the next person
    /// "fixes" the path by hand and the link to the source is lost.
    #[test]
    fn artwork_is_marked_as_generated() {
        let svg = svg_text();
        assert!(
            svg.contains("tools/trace_icon.py"),
            "the SVG should say it is generated by the tracer"
        );
        assert!(
            svg.contains("描摹"),
            "the SVG should note the artwork is traced, not hand-drawn"
        );
    }

    /// The traced bubbles carry the official shape: one evenodd path holding the
    /// outer outlines plus the eyes (as holes), drawn with cubic curves.
    #[test]
    fn traced_bubbles_use_one_evenodd_path_with_curves() {
        let svg = svg_text();
        let marker = bubble_path_start(svg);
        let start = svg[..marker].rfind("<path").expect("the path element");
        let end = svg[start..].find("/>").map(|o| start + o + 2).unwrap();
        let element = &svg[start..end];

        assert!(
            element.contains(r##"fill="#FFFFFF""##),
            "the bubbles are white"
        );
        assert!(element.contains('C'), "the outline should be curved");
        // Closed, and made of several subpaths: the two outlines plus the eyes
        // (the eyes are holes, punched out by `evenodd`).
        assert!(element.ends_with("Z\"/>"), "the path should be closed");
        assert!(
            element.matches('M').count() >= 3,
            "expected the outlines and the eyes as subpaths, found {} starts",
            element.matches('M').count()
        );
    }

    /// The brand green is the tile; the bubbles are white and drawn on top.
    #[test]
    fn background_is_a_green_tile_with_white_bubbles() {
        let svg = svg_text();

        let tile = svg
            .find(r##"<rect width="48" height="48""##)
            .expect("a full-size background tile");
        assert!(
            svg[tile..].starts_with(r##"<rect width="48" height="48" rx="10.7" fill="#07C160"/>"##),
            "the tile should be the brand green with the source icon's corner radius"
        );
        assert!(
            bubble_path_start(svg) > tile,
            "the bubbles must be drawn on top of the tile"
        );
    }

    /// The mark must use the WeChat green, not an arbitrary one.
    #[test]
    fn logo_uses_the_wechat_green() {
        assert!(
            svg_text().contains("#07C160"),
            "logo should use the brand green #07C160"
        );
    }

    /// A malformed SVG would render nothing, leaving a blank slot in the title
    /// bar. The structure is checked here; `build.rs` additionally fails the
    /// build if the SVG does not parse.
    #[test]
    fn logo_svg_is_well_formed() {
        let svg = svg_text();
        assert!(svg.trim_start().starts_with("<svg"), "missing <svg> root");
        assert!(svg.contains("viewBox="), "missing viewBox");
        assert!(svg.trim_end().ends_with("</svg>"), "unclosed <svg>");
        assert_eq!(svg.matches("<svg").count(), 1, "expected one <svg> root");
    }

    /// The generated PNG must be a decodable, non-empty square image — a blank
    /// or corrupt raster would show as an empty box in the title bar.
    #[test]
    fn rendered_png_is_decodable_and_square() {
        let png = assets::logo_png_bytes();
        assert_eq!(&png[..8], b"\x89PNG\r\n\x1a\n", "not a PNG");

        // IHDR width/height are big-endian u32 at offsets 16 and 20.
        let width = u32::from_be_bytes(png[16..20].try_into().unwrap());
        let height = u32::from_be_bytes(png[20..24].try_into().unwrap());
        assert_eq!(width, height, "logo PNG should be square");
        assert!(width >= 192, "logo PNG too small to look sharp: {width}");
        assert!(png.len() > 1000, "logo PNG looks empty");

        // The raster is complete (not cut off mid-stream).
        let iend = png.len() - 12;
        assert_eq!(&png[iend + 4..iend + 8], b"IEND", "PNG is truncated");
    }
}
